# Generated by Django 4.1.1 on 2024-04-19 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='statis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('cp', models.CharField(max_length=10)),
                ('trestbps', models.CharField(max_length=10)),
                ('cholestrol', models.CharField(max_length=10)),
                ('fbs', models.CharField(max_length=10)),
                ('restecg', models.CharField(max_length=10)),
                ('thalach', models.CharField(max_length=10)),
                ('exang', models.CharField(max_length=10)),
                ('oldpeak', models.CharField(max_length=10)),
                ('slope', models.CharField(max_length=10)),
                ('ca', models.CharField(max_length=10)),
                ('thal', models.CharField(max_length=10)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
