# Generated by Django 4.1.1 on 2024-04-21 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorsugg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.IntegerField()),
                ('emailid', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=1000)),
                ('Status', models.BooleanField(default=False)),
                ('Doctorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
