# Generated by Django 4.1.1 on 2024-04-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_doctorsugg'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsugg',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctorimages/'),
        ),
    ]
