# Generated by Django 4.1.1 on 2024-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0005_alter_appoint_appointmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='Description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='timeofappointment',
            field=models.CharField(max_length=50),
        ),
    ]
